<a href="https://colab.research.google.com/github/hemilkaklotar/pytorch-cv-pracs/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor.shape, tensor

(torch.Size([7, 7]),
 tensor([[0.4989, 0.3033, 0.2418, 0.4344, 0.9534, 0.6473, 0.3408],
         [0.2838, 0.6563, 0.7470, 0.8789, 0.4940, 0.1160, 0.9301],
         [0.6722, 0.1466, 0.0317, 0.0298, 0.5098, 0.5800, 0.8717],
         [0.7224, 0.0705, 0.4592, 0.6961, 0.9882, 0.6168, 0.9101],
         [0.2894, 0.8833, 0.1862, 0.6050, 0.2855, 0.6725, 0.4103],
         [0.1470, 0.2733, 0.8252, 0.3784, 0.8354, 0.0948, 0.2487],
         [0.6565, 0.1073, 0.7510, 0.0792, 0.2616, 0.4295, 0.8772]]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_b = torch.rand(1,7)
print(f"1st tensor shape: {tensor.shape}")
print(f"2nd tensor shape: {tensor_b.shape}")

# Perform matrix multiplication
print(f"\nneed transpose of 2nd tensor in order to do matrix multiplication.")
print(f"2nd tensor Transposed shape: {tensor_b.T.shape}")
matrix_mul_of_ab = torch.matmul(tensor, tensor_b.T)
print(f"Matrix multiplication is {matrix_mul_of_ab}")



1st tensor shape: torch.Size([7, 7])
2nd tensor shape: torch.Size([1, 7])

need transpose of 2nd tensor in order to do matrix multiplication.
2nd tensor Transposed shape: torch.Size([7, 1])
Matrix multiplication is tensor([[1.6427],
        [1.6575],
        [1.2022],
        [2.0897],
        [1.0140],
        [1.6508],
        [1.5477]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 37

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(7,7)
print(f"1st tensor: {tensor_1}")

torch.manual_seed(RANDOM_SEED)
tensor_2 = torch.rand(1,7)
print(f"2nd tensor: {tensor_2}")
transposed_2nd_tensor = tensor_2.T
print(f"transposed 2nd tensor : {transposed_2nd_tensor}")

# Matrix multiply tensors
print(f"shape of 1st & 2nd tensors : {tensor_1.shape} and {transposed_2nd_tensor.shape}")
mat_mul_with_manual_seed = torch.matmul(tensor_1, transposed_2nd_tensor)
print(f"matrix multiplication is {mat_mul_with_manual_seed}")

1st tensor: tensor([[0.7911, 0.6419, 0.8091, 0.1659, 0.3555, 0.6189, 0.9651],
        [0.2761, 0.7416, 0.6938, 0.1613, 0.1365, 0.4800, 0.9127],
        [0.8418, 0.2175, 0.1866, 0.0027, 0.8767, 0.2960, 0.9326],
        [0.8905, 0.6146, 0.0860, 0.5331, 0.3527, 0.6471, 0.3534],
        [0.6490, 0.4872, 0.3819, 0.0786, 0.5635, 0.4387, 0.7845],
        [0.9706, 0.4670, 0.2574, 0.8911, 0.5720, 0.1148, 0.2160],
        [0.5119, 0.9640, 0.9593, 0.7593, 0.3695, 0.0037, 0.6732]])
2nd tensor: tensor([[0.7911, 0.6419, 0.8091, 0.1659, 0.3555, 0.6189, 0.9651]])
transposed 2nd tensor : tensor([[0.7911],
        [0.6419],
        [0.8091],
        [0.1659],
        [0.3555],
        [0.6189],
        [0.9651]])
shape of 1st & 2nd tensors : torch.Size([7, 7]) and torch.Size([7, 1])
matrix multiplication is tensor([[3.1610],
        [2.5090],
        [2.3520],
        [2.1240],
        [2.3772],
        [1.9067],
        [2.7092]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU

tensor_on_gpu_1 = torch.rand(2, 3).to(device)
tensor_on_gpu_2 = torch.rand(2, 3).to(device)
tensor_on_gpu_1, tensor_on_gpu_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_A = tensor_on_gpu_1
tensor_B = tensor_on_gpu_2.T
mat_mulx = torch.matmul(tensor_A, tensor_B)
mat_mulx, mat_mulx.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
m_max = mat_mulx.max()
# Find min
m_min = mat_mulx.min()
m_max, m_min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
m_argmax = mat_mulx.argmax()

# Find arg min
m_argmin = mat_mulx.argmin()
m_argmax, m_argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_rand_1 = torch.rand(1,1,1,10)

# Remove single dimensions
removed_single_dim_tensor = tensor_rand_1.squeeze()

# Print out tensors and their shapes
print(tensor_rand_1, tensor_rand_1.shape, end="\n")
print(removed_single_dim_tensor, removed_single_dim_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
