<a href="https://colab.research.google.com/github/hemilkaklotar/pytorch-cv-pracs/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [ ]:
print("Learning Pytorch")

In [ ]:
!nvidia-smi

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

## introduction to tensors

### creating tensors

In [ ]:
#scaler
scaler = torch.tensor(7)
scaler

In [ ]:
scaler.ndim

In [ ]:
# Get tensor back as python int
scaler.item()

In [ ]:
# vector

vector = torch.tensor([7,7])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

In [ ]:
MATRIX.ndim

In [ ]:
MATRIX[1]

In [ ]:
MATRIX.shape

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                          [3,6,9],
                           [2,4,5]]])
TENSOR

In [ ]:
TENSOR.ndim

In [ ]:
TENSOR.shape

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random nubmers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers



In [ ]:
# Create a random tensor of size (3,4)..

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

In [ ]:
random_tensor.ndim

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

In [ ]:
ones = torch.ones(size=(3,4))
ones

In [ ]:
ones.dtype

In [ ]:
random_tensor.dtype

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() is deprecated, use torch.arange()
one_to_ten = torch.arange(start=0,end=11, step=1)
one_to_ten

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

### Tensor datatypes
** Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # what datatypes is? like float32 float16
                                device=None, # what device is your tensor on
                                requires_grad=False) # whetherv or not to track gradients
float_32_tensor , float_32_tensor

In [ ]:
float_32_tensor.dtype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

In [ ]:
float_integration = float_16_tensor * float_32_tensor
float_integration

In [ ]:
float_integration.dtype

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor


In [ ]:
float_32_tensor * int_32_tensor

### Getting information from tensor

1. Tensor not right datatype - to do get datattype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") #tenosr.size() is also same result
print(f"Device tensor is on")

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix Multiplication

In [ ]:
# create a tensor
tensor_1 = torch.tensor([1,2,3])
tensor_1 + 10

In [ ]:
tensor_1 * 10

In [ ]:
# subtract 10
tensor_1 - 10

In [ ]:
# try out PyTorch in-built functions
torch.mul(tensor_1, 10)

In [ ]:
torch.add(tensor_1, 100)

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deeplearning

1. Element wise multiplicattion
2. Matrix multiplication (dot product)


In [ ]:
# Element wise multiplication
print(tensor_1 , "*" , tensor_1)
print(f"Equals: {tensor_1 * tensor_1}")

In [ ]:
# Matrix multiplication
%%time
torch.matmul(tensor_1, tensor_1) # we can use `tenser_1 @ tensor_1` also for matmul

In [ ]:
# Matrix multiplication by hand
# 1 * 1 +  2 * 2 + 3 * 3

%%time
value = 0
for i in range(len(tensor_1)):
  value += tensor_1[i] * tensor_1[i]
print(value)

In [ ]:
torch.matmul(torch.rand(3,10), torch.rand(10,3)).shape

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A, tensor_B) is same as matmul
# torch.matmul(tensor_A, tensor_B)


to fix our tensor shape issues , we can manipulate the shape of one our tensors using shapes

A **transpose** switches the axes of dimenstions of a given tensor

In [ ]:
tensor_B.shape

In [ ]:
tensor_B.T.shape, tensor_B.T # .T for transpose

In [ ]:
#  matrix multiplication operations works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1,100,10)
x

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
torch.sum(x), x.sum()

### Finding the positional min and max

In [ ]:
x

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor where the minimum value occurs
x.argmin()

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine muliple  tensors on top of each otehr (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

In [ ]:
# changing z changes x (because a view of a tensor shaeres the same memory as the original input)
z[:, 0] = 5
z, x

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

In [ ]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

In [ ]:
# torch.unsqueeze() - adds a single dimensions to a target tensor at a specific dim (dimensions)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

In [ ]:
# Torch.permute - rearranges the dimensions of target tensor in specified order
x_original = torch.rand(size=(224,224,3)) # [height , width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permute = x_original.permute(2, 0 ,1) # shifts axis 0->1 , 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permute.shape}") # [colour_channels, height, width]


In [ ]:
x_permute[0,0,0]

In [ ]:
x_original[0,0,0]

In [ ]:
x_original[0,0,0] = 5775
x_permute[0,0,0]

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [ ]:
# Let's index on our new tensor
x[0]

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

In [ ]:
# You can also use ":" select "all" of a target dimension
x[:, 0]

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimensions
x[:, :,1]

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1 st and 2nd dimension
x[:, 1, 1]

In [ ]:
# get index 0 of oth and 1st dimension and all values of 2nd dimension
x[0, 0, :]

In [ ]:
# index on x to return 9
x[:, 2, 2]

In [ ]:
# index on x to return 3, 6, 9
x[:, :, 2]

## PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.
and because of this, PyTorch has functionality to interact with it.

* Data in NumPy,  want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `tensor.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch data tyep will be float64 need to convert into usable datatype using .type(torch.float32)
array, tensor

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

## Reproduciblility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.
Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

In [ ]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computationan on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good)


### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your GPU = takes a bit setup and requires the investment of purchasing
3. Use cloud computing - GCP, AWS, Azure these services allow you to rent computers on the cloud and access them

In [ ]:
!nvidia-smi

Mon Apr  1 17:33:01 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8              1W /   50W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# Check for GPU access with Pytorch

import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on the GPU if available, else default to CPU


In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using GPU results in faster computations.


In [ ]:
# create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print (tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available regardless is gpu available or not!
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])